### ISSUE TITLE
Problem with text color on  [Tribe_events]

### ISSUE THREAD

**Issue by seowkw** [afragen/the-events-calendar-category-colors#75]
Hi,

I need help on the events calendar category color, the border and background color works fine, but the text color only display in light green color, regardless of the color I choose from the list, black, white or grey, it will only show as light green, this happened on [Tribe_events] short code including other views format such as list, photos, etc.

As for Short code [Tribe_mini_calendar], the list of events will show the correct color scheme.

I'm attaching the screen capture.

![image](https://cloud.githubusercontent.com/assets/25026628/21800559/27873b98-d759-11e6-9225-bdbb93270aa3.png)
![image](https://cloud.githubusercontent.com/assets/25026628/21800577/34868a24-d759-11e6-9c0d-0f2fb3b686fd.png)

Appreciate of any help.

Thanks & Best Regards,
Seow

**Comment by afragen** [comment]
What's happening is that you have set the green text color using the Customizer. Unfortunately, at this time, the Customizer inserts its changes as inline CSS at the bottom of the page. Because of this it overrides the CSS that Category Colors produces. 

At this time the only _fix_ is to remove all Events Calendar Customizer CSS by using the following code. This will remove all Events Calendar Customizer CSS.

```php
add_filter( 'tribe_events_pro_customizer_css_template', '__return_empty_string', 20 );
```

Once this Customizer CSS is added in a different manner the 2 should work together. Sorry I have no timeline.

**Comment by seowkw** [comment]
Hi Afragen,

Thank you for your reply and sorry for the trouble, as I'm very new on coding, can you list done the step by step on how to do it?

Sorry for the inconveniences.

Thanks,
Seow

**Comment by afragen** [comment]
If you wish to use the code provided above, place it in your theme's `functions.php` file. If you don't like the results just remove it. Hopefully a better implementation  of the Events Calendar Customizer integration that doesn't conflict will be forthcoming.

**Comment by seowkw** [comment]
Hi Andy,

I managed to find the customize on events calendar under link text.

Thanks for the advice.

Cheers,
Seow
