### ISSUE TITLE
Featured event font turns white

### ISSUE THREAD

**Issue by edieann** [afragen/the-events-calendar-category-colors#79]
My monthly calendar view looks great in black text with colored side bar but as soon as I make an event featured, the text turns white and can't be read. What is wrong?
![calendar error](https://cloud.githubusercontent.com/assets/28478324/25771105/dbbe40b8-31fc-11e7-8e39-9bfc2d5c5f44.jpg)

**Comment by afragen** [comment]
Can you share the calendar URL?

**Comment by KZeni** [comment]
This is the behavior for The Events Calendar when you use the full styles and have it set to use a featured event which is then in a category that has the background set to transparent.

By default the full styles for The Events Calendar turns the text white & the background blue for featured events. Meanwhile, it appears The Events Calendar Category Colors doesn't account for the fact that `#tribe-events-content table.tribe-events-calendar .type-tribe_events.tribe-event-featured .tribe-events-month-event-title a { color: #fff }` is being applied (it does currently overwrite the default featured background & border colors).

I think this plugin should overwrite the text color just like it already is for the border & background. Then, additional styling can be added via the site's theme CSS as needed. This appears to be the simplest fix.

Otherwise, including a new "Add Featured Style" for each category which then lets each category color setup when also be able to have a variant that's used when an event in that category is then set as featured. This would provide more functionality, and keep things within the site admin when it comes to keeping featured events styled differently.

**Comment by KZeni** [comment]
As an aside, a quick path for your site would be to add `#tribe-events-content table.tribe-events-calendar .type-tribe_events.tribe-event-featured .tribe-events-month-event-title a { color:inherit!important; }` so it takes on the text color of the category instead of using the default featured event styling.

**Comment by afragen** [comment]
Thanks, great info.

A background set to transparent would never show white text well anyway. 

Still waiting to hear from OP.

**Comment by afragen** [comment]
This should be fixed in latest `develop` branch.
