### ISSUE TITLE
Still showing colours when past events are hidden.

### ISSUE THREAD

**Issue by EventosDonosti** [afragen/the-events-calendar-category-colors#93]
I added code to be able to hide past events (as per provided by Tribe Events) but I still see the colours of those past events as per the next image:

![issue](https://user-images.githubusercontent.com/38850574/39417016-b369f498-4c51-11e8-84fa-d9d317ae655b.jpg)

Is there a way you could help me removing the colours from past events?

**Comment by afragen** [comment]
On first glance it appears that hiding the events is done with a `display:none`.

In order to remove the CSS from Category Colors you will likely need to readjust the CSS selector to something on a higher order than this plugin’s CSS selects.

I could give a better answer if you shared both your calendar URL and the code used to hide old events.
